#!/bin/sh
stack clean
type-parser library haskell ../../TestLibraryDefinition TestLibraryTenkei.hs
stack build
cp "$(find ../.stack-work/dist -name 'libHShaskell-test-lib*.dylib')" libtest-library.dylib
install_name_tool -id libtest-library.dylib libtest-library.dylib
